apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcp-cloud-run-example
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    spec:
      containers:
        - image: docker.io/primetimetran/gcp-cloud-run-example:latest